# Generated by Django 5.1.6 on 2025-03-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_rsvp'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='asset',
            field=models.ImageField(blank=True, default='events_asset/default_img.jpg', null=True, upload_to='tasks_asset'),
        ),
    ]
