# Generated by Django 5.1.6 on 2025-03-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='asset',
            field=models.ImageField(blank=True, default='tasks_asset/img1.jpeg', null=True, upload_to='tasks_asset'),
        ),
    ]
